// Common Report Header Component for PDF generation
// This module exports functions to draw the header on PDF documents

/**
 * Draws the standard report header with logo and contact info
 * @param {jsPDF} doc - The jsPDF document instance
 * @param {string} logoPath - Path to the logo image (default: '/downloads/Log.png')
 */
export const drawReportHeader = (doc, logoPath = '/downloads/Log.png') => {
  // Add logo image
  try {
    doc.addImage(logoPath, 'PNG', 15, 8, 35, 13);
  } catch (e) {
    // Fallback to text if image fails
    doc.setFontSize(22);
    doc.setFont(undefined, "bold");
    doc.setTextColor(55, 65, 81);
    doc.text("immort", 15, 18);
    doc.setTextColor(20, 184, 166);
    doc.text("igen", 48, 18);
  }
  
  // Contact info section
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.setFont(undefined, "normal");
  
  // Phone icon indicator and number
  doc.setFillColor(107, 114, 128);
  doc.circle(82, 13, 1.5, 'F');
  doc.text("+91 98552 73727", 86, 15);
  
  // Email icon indicator
  doc.setFillColor(107, 114, 128);
  doc.circle(122, 13, 1.5, 'F');
  doc.text("contact@immortigen.com", 126, 15);
  
  // Website icon indicator
  doc.setFillColor(107, 114, 128);
  doc.circle(168, 13, 1.5, 'F');
  doc.text("www.immortigen.com", 172, 15);
  
  // Horizontal line below header
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.5);
  doc.line(15, 25, 195, 25);
};

/**
 * Draws the report footer with page numbers
 * @param {jsPDF} doc - The jsPDF document instance
 * @param {number} currentPage - Current page number
 * @param {number} totalPages - Total number of pages
 */
export const drawReportFooter = (doc, currentPage, totalPages) => {
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text(`Page ${currentPage} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: "center" });
  doc.text("Generated by IMMORTIGEN Health System", pageWidth / 2, pageHeight - 5, { align: "center" });
};

/**
 * Status color configurations for risk levels
 */
export const statusColors = {
  H: { bg: { r: 239, g: 68, b: 68 }, text: "High Risk", bgHex: "#EF4444" },
  M: { bg: { r: 251, g: 146, b: 60 }, text: "Moderate Risk", bgHex: "#FB923C" },
  L: { bg: { r: 34, g: 197, b: 94 }, text: "Low Risk", bgHex: "#22C55E" }
};

/**
 * Draws a risk score bar with three segments (High, Moderate, Low)
 * @param {jsPDF} doc - The jsPDF document instance
 * @param {number} x - X position
 * @param {number} y - Y position
 * @param {string} status - Risk status ('H', 'M', or 'L')
 */
export const drawRiskScoreBar = (doc, x, y, status) => {
  const barWidth = 90;
  const barHeight = 7;
  const segmentWidth = barWidth / 3;
  
  const segments = [
    { color: statusColors.H.bg, label: "High Risk", status: "H" },
    { color: statusColors.M.bg, label: "Moderate Risk", status: "M" },
    { color: statusColors.L.bg, label: "Low Risk", status: "L" }
  ];
  
  segments.forEach((segment, index) => {
    const segX = x + (index * segmentWidth);
    const isActive = segment.status === status;
    
    if (isActive) {
      // Active segment with full color
      doc.setFillColor(segment.color.r, segment.color.g, segment.color.b);
      doc.roundedRect(segX, y, segmentWidth - 2, barHeight, 2, 2, "F");
      
      // Text on active segment
      doc.setFontSize(6);
      doc.setFont(undefined, "bold");
      doc.setTextColor(255, 255, 255);
      doc.text(segment.label, segX + (segmentWidth - 2) / 2, y + barHeight / 2 + 2, { align: "center" });
    } else {
      // Inactive segment with lighter color
      doc.setFillColor(229, 231, 235);
      doc.roundedRect(segX, y, segmentWidth - 2, barHeight, 2, 2, "F");
      
      // Lighter text
      doc.setFontSize(6);
      doc.setFont(undefined, "normal");
      doc.setTextColor(156, 163, 175);
      doc.text(segment.label, segX + (segmentWidth - 2) / 2, y + barHeight / 2 + 2, { align: "center" });
    }
  });
};

/**
 * Draws a risk badge
 * @param {jsPDF} doc - The jsPDF document instance
 * @param {number} x - X position
 * @param {number} y - Y position
 * @param {string} status - Risk status ('H', 'M', or 'L')
 * @param {number} width - Badge width (default: 30)
 * @param {number} height - Badge height (default: 7)
 */
export const drawRiskBadge = (doc, x, y, status, width = 30, height = 7) => {
  const config = statusColors[status];
  
  // Draw rounded rectangle badge
  doc.setFillColor(config.bg.r, config.bg.g, config.bg.b);
  doc.roundedRect(x, y, width, height, 2, 2, "F");
  
  // Badge text
  doc.setFontSize(7);
  doc.setFont(undefined, "bold");
  doc.setTextColor(255, 255, 255);
  doc.text(config.text, x + width / 2, y + height / 2 + 2, { align: "center" });
};

export default {
  drawReportHeader,
  drawReportFooter,
  statusColors,
  drawRiskScoreBar,
  drawRiskBadge
};
